[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25"
macroquad = "0.4.14"
minifb = "0.28"
mlua = { version = "0.9", features = ["lua54", "vendored"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
rodio = "0.18"


